### ISSUE TITLE
Align possible states Release.status = {Incomplete|ToBeProcessed|Processed}

### ISSUE THREAD

**Issue by nicolabortignon** [TracklistMe/server#15]
Incomplete: the release has some missing files, can be tracks without a file, or missing the COVER. It does on other hands make sense at the database level. 
It can be a generate for a temporary, incomplete release.

ToBeProcessed: the release is in the database, with all meaningful file associate for each track, but the processor is required to process at least one of the tracks.
One or more of the tracks should be in state ToBeProcessed.

Processed. The release is consistent. All the snippets are available for each track. Mp3 and Wav file are available too. All the files associates are in the Releases/:id folder in the cdn.

**Comment by mziccard** [comment]
Added also PROCESSING_FAILED status.
Closed with 5266c6d
