### ISSUE TITLE
Align possible states Track.status = {Incomplete|ToBeProcessed|Processed}

### ISSUE THREAD

**Issue by nicolabortignon** [TracklistMe/server#16]
Incomplete: the track has no file associated Or there are other mandatory fields missing.

ToBeProcessed: the track has all the mandatory fields completed, successfully pass any validation, and has a file associated, but the file has not being processed yet.

Processed. The file associated with the track has been processed correctly and all the filers are now available and linked in the db entry of the track

**Comment by mziccard** [comment]
Actually, Track.status={Incomplete|ToBeProcessed|Processed|ProcessingFailed}
if Track.status == ProcessingFailed the errorMessage contains some info about the error.
Closed with 5266c6d
